# $OpenBSD$
#		|----------------------------------------------------------|
COMMENT =	A web application framework for writing web APIs in C.

DISTNAME =	kore-1.2.3

GH_ACCOUNT =	jorisvink
GH_PROJECT =	kore
GH_TAGNAME =	1.2.3-release

CATEGORIES =	www

HOMEPAGE =	https://kore.io/

MAINTAINER =	Aaron Poffenberger <akp@hypernote.com>

# ISC
PERMIT_PACKAGE_CDROM =	Yes

WANTLIB =		c crypto ssl z

USE_GMAKE =		Yes

.include <bsd.port.mk>
